port = "8888"
secret = "test"

[mysql]
host = ""
user = ""
password = ""
db = ""
port = ""

[redis]
ip = ""
port = ""

[wechat]
appid = "wx577c587e3ea2cbd5"
secret = "d65bd9243ecc159e967ee6f611fcbe54"